---
title: "velosipedi"
author: "Igor"
date: "9/19/2020"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE, cache=FALSE)
```


```{r}
library(tidyverse)
library(lubridate)
library(viridis)
```

```{r}
df <-  readr::read_csv("https://raw.githubusercontent.com/discindo/natochak/master/mvr-data.csv")
```

```{r}
accidents <- readr::read_csv("https://raw.githubusercontent.com/discindo/natochak/master/mvr-data.csv")
```

```{r}
#keep the traffic accidents
traffacc <- accidents %>%
  #separate Date of event; having months as observations might be useful.
  separate(DateOfEvent, c("Day", "Month", "Year"), sep = "\\.", remove = FALSE) %>%
  #separate hours:mins, make numeric
  separate(Hour, c("H", "M"), sep = "\\:", remove = FALSE) %>%
  mutate(Hours = as.numeric(H)) %>%
  #filter so we keep just the traffic accidents
  filter(Event == "сообраќајна незгода") %>% 
  mutate(Outcome = ordered(Outcome, levels = c("непознато", "повреда", "тешка повреда", "животна опасност", "смрт")))
```

```{r}
view(traffacc)
```


```{r}
#deal with the municipalities
traffacc <- traffacc %>% 
  mutate(Mun2 = ifelse(is.na(Mun), Place, Mun)) %>%
  mutate(MunLatin = stringi::stri_trans_general(Mun2, 'latin')) %>%
  mutate(MunLatin = ifelse(MunLatin == "Ǵorče Petrov", "Gjorče Petrov", MunLatin))

```

```{r}
# time as time!
traffacc <- traffacc %>% 
  mutate(DateTime= parse_date_time(paste(DateOfEvent, Hour, sep=" "), orders="dmy HM")) %>% 
  mutate(TimeHM=parse_time(x = Hour, format="%H:%M")) %>%
  mutate(TimeH=hour(x = DateTime)) %>% 
  mutate(TypeOfRoadMK=case_when(
    TypeOfRoad == 'Open'  ~ 'Отворен',
    TypeOfRoad == 'Rural' ~ 'Селски',
    TypeOfRoad == 'Urban' ~ 'Градски'
  ))
```

Графикон за сообраќајни несреќи со велосипеди 
```{r, fig.width=10}
ggplot(traffacc, aes(x=AgeV1, y=TimeHM, fill = Outcome, ordered = TRUE)) +
  geom_point(size = 5, alpha = 0.2, pch=21) +
  labs(fill="Вид на повреда") +
  scale_color_viridis(discrete = TRUE, option = "D") +
  facet_wrap("TypeOfRoadMK", ncol=3) +
  theme(legend.position="top") +
  scale_y_time() +
  labs(title="Сообраќајни незгоди по години на велосипедист и час во денот",
       subtitle="2019 година",
          x = "Возраст на велосипедист", y = "Час од денот во кој е случена незгода")
```



